#   - Net::Snort::Parser -
#   This spec file was automatically generated by cpan2rpm [ver: 2.028]
# and suplimented manually by Earl Sammons
#   The following arguments were used:
#       ../SOURCES/Net-Snort-Parser-1.29.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/

%define pkgname Net-Snort-Parser
%define filelist %{pkgname}-%{version}-filelist
%define NVR %{pkgname}-%{version}-%{release}
%define maketest 1

Name:      perl-Net-Snort-Parser
Summary:   Net-Snort-Parser - Perl interface to parsing snort rules
Version:   1.41
Release:   hw.1
Source:    Net-Snort-Parser-%{version}.tar.gz
Vendor:    Brian Caswell <bmc@shmoo.com>
Packager:  Arix International <cpan2rpm@arix.com>
License:   Artistic
Group:     Applications/CPAN
Url:       http://www.shmoo.com/~bmc/software/snortconfig
Buildroot: %{_tmppath}/%{name}-%{version}-%(id -u -n)
Buildarch: noarch
Prefix:    %(echo %{_prefix})

%description
Net::Snort::Parser::File is a module that provides a mechanism for parsing snort rules, handling most of the "isms" that the snort parser forces on application developers.

Programmers that use this module should be familar with the snort rules format, since many requirements of the rules language are implied by this module.

Copyright (C) 2003 Brian Caswell <bmc@shmoo.com>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
   This product includes software developed by Brian Caswell.
4. The name of the author may not be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#
# This package was generated automatically with the cpan2rpm
# utility.  To get this software or for more information
# please visit: http://perl.arix.com/
#

%prep
%setup -q -n %{pkgname}-%{version} 
chmod -R u+w %{_builddir}/%{pkgname}-%{version}

%build
grep -rsl '^#!.*perl' . |
grep -v '.bak$' |xargs --no-run-if-empty \
%__perl -MExtUtils::MakeMaker -e 'MY->fixin(@ARGV)'
CFLAGS="$RPM_OPT_FLAGS"
%{__perl} Makefile.PL `%{__perl} -MExtUtils::MakeMaker -e ' print qq|PREFIX=%{buildroot}%{_prefix}| if \$ExtUtils::MakeMaker::VERSION =~ /5\.9[1-6]|6\.0[0-5]/ '`
%{__make} 
%if %maketest
%{__make} test
%endif

%install
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}

%__mkdir_p -m0755 %{buildroot}/hw/etc
%__install -m0644 examples/HONEYNET.config %{buildroot}/hw/etc/snortconfig.conf
%{makeinstall} `%{__perl} -MExtUtils::MakeMaker -e ' print \$ExtUtils::MakeMaker::VERSION <= 6.05 ? qq|PREFIX=%{buildroot}%{_prefix}| : qq|DESTDIR=%{buildroot}| '`

cmd=/usr/share/spec-helper/compress_files
[ -x $cmd ] || cmd=/usr/lib/rpm/brp-compress
[ -x $cmd ] && $cmd

# SuSE Linux
if [ -e /etc/SuSE-release -o -e /etc/UnitedLinux-release ]
then
    %{__mkdir_p} %{buildroot}/var/adm/perl-modules
    %{__cat} `find %{buildroot} -name "perllocal.pod"`  \
        | %{__sed} -e s+%{buildroot}++g                 \
        > %{buildroot}/var/adm/perl-modules/%{name}
fi

# remove special files
find %{buildroot} -name "perllocal.pod" \
    -o -name ".packlist"                \
    -o -name "*.bs"                     \
    |xargs -i rm -f {}

# no empty directories
find %{buildroot}%{_prefix}             \
    -type d -depth                      \
    -exec rmdir {} \; 2>/dev/null

%{__perl} -MFile::Find -le '
    find({ wanted => \&wanted, no_chdir => 1}, "%{buildroot}");
    print "%doc  Snort INSTALL README examples";
#    print "%doc  Snort examples README";
    for my $x (sort @dirs, @files) {
        push @ret, $x unless indirs($x);
        }
    print join "\n", sort @ret;

    sub wanted {
        return if /auto$/;

        local $_ = $File::Find::name;
        my $f = $_; s|^\Q%{buildroot}\E||;
        return unless length;
        return $files[@files] = $_ if -f $f;

        $d = $_;
        /\Q$d\E/ && return for reverse sort @INC;
        $d =~ /\Q$_\E/ && return
            for qw|/etc %_prefix/man %_prefix/bin %_prefix/share|;

        $dirs[@dirs] = $_;
        }

    sub indirs {
        my $x = shift;
        $x =~ /^\Q$_\E\// && $x ne $_ && return 1 for @dirs;
        }
    ' > %filelist

[ -z %filelist ] && {
    echo "ERROR: empty %files listing"
    exit -1
    }

%pre

%post

%postun

%clean
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}

%files -f %filelist
%defattr(-,root,root)
%attr(0644, root, root) /hw/etc/snortconfig.conf
%attr(0755, root, root) /usr/bin/snortconfig

%changelog
* Fri Nov 23 2007 Earl Sammons <esammons@hush.com>
- Upped version to match new release

* Tue Feb 13 2007 Earl Sammons <esammons@hush.com>
- Upped version to match new release
- Added Makefile support

* Thu Nov 02 2006 Earl Sammons <esammons@hush.com>
- Upped version to match new release for Will Metcalfs patch
- Fixed postun count conditional
- Added /hw/etc/snortconfig.conf to files
- Added /usr/bin/snortconfig.conf to files to correct perms
- Moved making of /hw/etc up to install where it belongs

* Wed Sep 06 2006 Earl Sammons <esammons@hush.com>
- Fixed test in postun for removal of config
- Added true statements in post and preun

* Sat Sep 02 2006 Earl Sammons <esammons@hush.com>
- Move conf from /hw/etc/snortconf/ to /hw/etc/

* Tue Jul 11 2006 Earl Sammons <esammons@hush.com>
- Updated for verison 1.32

* Wed Jun 14 2006 Earl Sammons <esammons@hush.com>
- Copying sampleconfig to /hw/etc/snortconfig
- Cleaning out /hw/etc/snortconfig on removal

* Tue Jun 13 2006 Earl Sammons <esammons@hush.com>
- Updated for verison 1.29

* Sat Feb 11 2006 Earl Sammons <esammons@hush.com>
- Initial build
