0fhoneywl.lss


                 Honeynet Project Honeywall Install CDROM
                             ROO Version 1.4-b3


            ######################################################
            #          !!!!! - W A R N I N G - !!!!!             #
            #  Continuing will overwrite existing Hard Drive(s)  #
            ######################################################

             Hit (return) key to overwrite existing hard drive...

